### ISSUE TITLE
qb-vehicleshop issue

### ISSUE THREAD

**Issue by sdosdosdos** [qbcore-fivem/qb-vehicleshop#11]
script error: @qb-vehicleshop/client.lua:80: bad argument #1 to `gsub` (string expected, got nil)
![image](https://user-images.githubusercontent.com/102893574/218565517-23b2c542-65cd-4928-a423-caacccd65e9d.png)

**Comment by tom-osborne** [comment]
This is most likely to be an error in your `vehicles.lua`

One of your vehicles either does not have a `price` or it has an incorrect value type.
