### ISSUE TITLE
SCRIPT ERROR: @qb-vehicleshop/client.lua:181: attempt to index a nil value (field '?')

### ISSUE THREAD

**Issue by xxUnknown13xx** [qbcore-fivem/qb-vehicleshop#13]
Not sure why I get this error after I do a test run.
![werror](https://user-images.githubusercontent.com/113321753/219802106-81ae5754-14d3-4715-8c24-a2318263a746.PNG)

**Comment by elpouletorange** [comment]
i had the same issue, trying to debug it and its gone lol

**Comment by Casitrompeta** [comment]
Does anyone know how to fix it? I get the same error since +1 month ago, help pls :)

**Comment by Shaine415** [comment]
> Not sure why I get this error after I do a test run. ![werror](https://user-images.githubusercontent.com/113321753/219802106-81ae5754-14d3-4715-8c24-a2318263a746.PNG)

Did you manage to sort this i have the exact same problem, Thankyou

**Comment by xxUnknown13xx** [comment]
> > Not sure why I get this error after I do a test run. ![werror](https://user-images.githubusercontent.com/113321753/219802106-81ae5754-14d3-4715-8c24-a2318263a746.PNG)
> 
> Did you manage to sort this i have the exact same problem, Thankyou

No but i just started to use a different sale script. 😅
