### ISSUE TITLE
Vehicles Wont Spawn

### ISSUE THREAD

**Issue by ChaseReeser** [qbcore-fivem/qb-vehicleshop#15]
Vehicles wont spawn when purchased or when selecting test drive. No errors in console.

**Comment by riffcity** [comment]
Same issue here, I can't seem to find a solution

**Comment by BansaGaming** [comment]
> Same issue here, I can't seem to find a solution

With what car or cars do you have that problem ?

**Comment by KaidenTheCEO** [comment]
Same but I get the error GetNetworkObject: no object by ID 0
