### ISSUE TITLE
SCRIPT ERROR: @qb-vehicleshop/client.lua:98 attempt to index a nil value (field ´Vehicles´)

### ISSUE THREAD

**Issue by Kroniez** [qbcore-fivem/qb-vehicleshop#18]
I added addon vehicles and added them to qbcore/shared/vehicles.lua and now I have the problem that I can no longer open the shop and I get this error:
SCRIPT ERROR: @qb-vehicleshop/client.lua:98 attempt to index a nil value (field 'Vehicles')
> getVehBrand (@qb-vehicleshop/client.lua:98)
> fn (@qbcore-vehicleshop/client.lua:255)

**Comment by megajkobe** [comment]
When you put your addon vehicle into the shared file did you put the brand in?
It should look something like this    
['blista'] = {
        ['name'] = 'Blista',
        **['brand'] = 'Dinka',**
        ['model'] = 'blista',
        ['price'] = 13000,
        ['category'] = 'compacts',
        ['categoryLabel'] = 'Compacts',
        ['hash'] = `blista`,
        ['shop'] = 'pdm',
    },

**Comment by Kroniez** [comment]
> When you put your addon vehicle into the shared file did you put the brand in? It should look something like this ['blista'] = { ['name'] = 'Blista', **['brand'] = 'Dinka',** ['model'] = 'blista', ['price'] = 13000, ['category'] = 'compacts', ['categoryLabel'] = 'Compacts', ['hash'] = `blista`, ['shop'] = 'pdm', },

yes i have it looks exactly like this only with the respective name for the car

**Comment by megajkobe** [comment]
What is the addon car called?

**Comment by Kroniez** [comment]
> What is the addon car called?

2020 Ford Mustang Shelby GT500     model name: forgt50020

**Comment by megajkobe** [comment]
Let me dig into this a bit and I will let you know

**Comment by rodrigogusmao** [comment]
any result ??

**Comment by NotOppi** [comment]
any news on this issue? Did you managed to solve it?

**Comment by NotOppi** [comment]
@megajkobe Would appreciate an update if you found anything.

**Comment by megajkobe** [comment]
I have not found anything. Everytime I try it with an add-on car I have had no issues
