### ISSUE TITLE
qb-vehicleshop error

### ISSUE THREAD

**Issue by HKA417** [qbcore-fivem/qb-vehicleshop#20]
[script:qb-vehiclesho] SCRIPT ERROR: @qb-vehicleshop/server.lua:433: qb-vehicleshop was unable to execute a query!
[script:qb-vehiclesho] Unknown column 'balance' in 'where clause'
[script:qb-vehiclesho] SELECT * FROM player_vehicles WHERE citizenid = ? AND balance > 0 AND financetime < 1 ["TPF65612"]
[script:qb-vehiclesho] > handler (@qb-vehicleshop/server.lua:433)
[script:qb-vehiclesho] > <unknown> (@oxmysql/dist/build.js:21832)
[script:qb-vehiclesho] > processTicksAndRejections (node:internal/process/task_queues:96)

**Comment by Rtextbook** [comment]
same

**Comment by Caillou456** [comment]
did you ever get it to work

**Comment by Rtextbook** [comment]
> did you ever get it to work
> 
> 
> 
> 
> 
> 

Yes I made it a public shop with higher rates. Than the online mech.

**Comment by Alpha1097** [comment]
how can i fix the problem i am getting the same error?
