### ISSUE TITLE
Assumed issue with syncing between players

### ISSUE THREAD

**Issue by Beaness0123** [qbcore-fivem/qb-vehicleshop#23]
On our dev-server there's an issue where most of the time, no cars spawn on display in the Vehicle Shop. 

It happens that they spawn in perfectly on my end, but when a friend joins he doesn't see anything.

Whenever they don't spawn in, we aren't getting the pop-up to buy/change or finance the cars either.

I'm clueless as to what it could be.
Can anybody help please?

Thanks in advance!

**Comment by xiknownxi** [comment]
im having the same  problem have u fixed it for have a fix?

**Comment by Beaness0123** [comment]
Hello,

Well yes, our issue seemed to be with qb-target conflicting with another
targeting script. It took hours upon hours to find, but it got fixed for us
by removing every other targetting script that interfered.

Really hope this helps!

Op do 1 jun. 2023 05:32 schreef xiknownxi ***@***.***>:

**Comment by xiknownxi** [comment]
thank u one more question is it targeting script it self or like an error with qb-target or could it be a another script that is using a different targeting script sorry if i sound dumb just trying to narrow it down

**Comment by xiknownxi** [comment]
we fixed it it was qb-target

**Comment by Beaness0123** [comment]
Hey there,

Yes you are right, it's purely an issue with qb-target and/or another
targetting script that messes with it. Glad it helped though, have fun!

Op do 1 jun. 2023 17:22 schreef xiknownxi ***@***.***>:

**Comment by xiknownxi** [comment]
thank u so much!

**Comment by xiknownxi** [comment]
it actully fixed for a little bit then broke again and we don't have any other target script idk whats going on :(

**Comment by Beaness0123** [comment]
Oh damn sorry to hear...
Do you have any errors in the f8 menu?
Did you backup the qb-target you currently have and placed a newer
version/unedited version in your files?




Op do 1 jun. 2023 18:30 schreef xiknownxi ***@***.***>:

**Comment by xiknownxi** [comment]
nothing from vehicle shop

**Comment by xiknownxi** [comment]
i replaced it the first time thats what fixed it then broke again

**Comment by xiknownxi** [comment]
so i just turned qb - target off by doing this setr UseTarget false and everything spawned but now we dont have a way to buy them through 3rd eye

**Comment by xiknownxi** [comment]
then relog and they still dont spawn in idk what to do

**Comment by xiknownxi** [comment]
idk what it could be

**Comment by Beaness0123** [comment]
Normally when you use vehicleshop there's a popup menu when you get close
to a car right?

You should look and disable that, and make sure you've installed qb-target
properly.

Although, that's what fixed it for me.

Op do 1 jun. 2023 19:04 schreef xiknownxi ***@***.***>:

**Comment by xiknownxi** [comment]
where do i disable it?

**Comment by Beaness0123** [comment]
I'm not completely sure but i recon it's in the vehicleshop folder.

Probably in the UI.

Op do 1 jun. 2023 19:47 schreef xiknownxi ***@***.***>:

**Comment by xiknownxi** [comment]
i cant  find it

**Comment by Beaness0123** [comment]
I'm not home atm so i can't really check...
It should be in there somewhere.

Op do 1 jun. 2023 20:08 schreef xiknownxi ***@***.***>:

**Comment by xiknownxi** [comment]
hey i know this is off topic i did fix the cars but we got a new setbelt script do u know to to make the qbcore one go again we deleted the files and the icon still shows up
