### ISSUE TITLE
script error 

### ISSUE THREAD

**Issue by Dawsondude2023** [qbcore-fivem/qb-vehicleshop#31]
https://github.com/qbcore-framework/qb-vehicleshop/blob/ad52945821d1a983d23a5180b874d64c4a522cf2/client.lua#LL110C1-L110C1
https://github.com/qbcore-framework/qb-vehicleshop/blob/ad52945821d1a983d23a5180b874d64c4a522cf2/client.lua#L238

![image](https://github.com/qbcore-framework/qb-vehicleshop/assets/115547663/13026355-2cff-4f08-a930-eb4db3648101)
this is error ^ when try and use menu

**Comment by Dawsondude2023** [comment]
fixed my issue 
DB ISSUE

**Comment by 275RP** [comment]
Im having this same issue how did you fix?
