### ISSUE TITLE
attempt to index a nil value (local 'data' )

### ISSUE THREAD

**Issue by ByAlexOrtiz** [qbcore-fivem/qb-vehicleshop#45]
hello, after restarting the server / script if I go to the truck store to see the dealer and switch between trucks, I get this error and I do not even see the menu, even so the other dealerships such as cars or aircraft works perfectly even if I get that error. Is there any possible solution?
![image](https://github.com/qbcore-framework/qb-vehicleshop/assets/58607105/a46946f5-2643-4d59-bc75-3b03aade4991)

**Comment by nico7710** [comment]
> 
hello, I have the same problem if anyone has a solution I am interested
