### ISSUE TITLE
Flying Vehicles for truchshop

### ISSUE THREAD

**Issue by ChristianBDev** [qbcore-fivem/qb-vehicleshop#5]
I went to the truckshop and the vehicles were floating with fresh qb-core install, I changed the minheight to 23.0 instead of 25.0 and its now on the floor.

Change line 248 in the qb-vehicleshop/Config.lua from ['minZ'] = 25.0 to ['minZ'] = 23.0

**Comment by MrTeaRexx** [comment]
im getting this with every vehicle no matter the changes, also can be triggered when a admin teleports, relogging works to reset them, but when you go to other locations this happens for me continuously
