### ISSUE TITLE
No way to sell used vehicles

### ISSUE THREAD

**Issue by TheOnlyNecro** [qbcore-fivem/qb-vehicleshop#51]
My players are complaining that there is no way to unload unwanted vehicles. They are aware of the resell point where they can put it out for sale and hope someone buys it but they want to just goto the dealership and unload it right away.

**Comment by vicktorviggo** [comment]
well https://github.com/qbcore-framework/qb-vehiclesales already has that feature
![image](https://github.com/qbcore-framework/qb-vehicleshop/assets/133223399/67685968-3077-4c92-98a3-50054db88ac9)

**Comment by TheOnlyNecro** [comment]
Yeah, that script relies on other players to buy the car. Where is the sell
point if you want to get rid of the car immediately?

**Comment by vicktorviggo** [comment]
if you look in the picture you have 2 options
