### ISSUE TITLE
SCRIPT ERROR: @qb-vehicleshop/client.lua:98: attempt to index a nul value (field '?')

### ISSUE THREAD

**Issue by virtuseee** [qbcore-fivem/qb-vehicleshop#53]
I was changing the vehicles in my qbcore/shared/vehicles.lua and got this error.

![image](https://github.com/qbcore-framework/qb-vehicleshop/assets/114982025/7e340d1b-b3a6-48e0-9824-83f26efca180)
![image](https://github.com/qbcore-framework/qb-vehicleshop/assets/114982025/747c6eda-45fe-4eea-b8cd-9f5b7ac8e16a)
![image](https://github.com/qbcore-framework/qb-vehicleshop/assets/114982025/dd50d4f8-83ca-4e84-92b6-36b020557fc9)

![image](https://github.com/qbcore-framework/qb-vehicleshop/assets/114982025/11400f01-225a-42bd-ba2c-f6789b4cc7d1)

This is my vehicles.lua I dont see any errors in here im just confused lol

QBShared = QBShared or {}

QBShared.Vehicles = {
    -- CToyota
    ['6X6LC'] = {
        ['name'] = '6X6LC',
        ['brand'] = 'Toyota',
        ['model'] = '6X6LC',
        ['price'] = 4000,
        ['category'] = 'toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `6X6LC`,
        ['shop'] = 'pdm',
    },
    ['21hilux4x4c'] = {
        ['name'] = 'Hilux 4x4 2021',
        ['brand'] = 'Toyota',
        ['model'] = '21hilux4x4c',
        ['price'] = 4000,
        ['category'] = 'toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `21hilux4x4c`,
        ['shop'] = 'pdm',
    },
    ['22TOYOTACOM'] = {
        ['name'] = 'Tocoma 2022',
        ['brand'] = 'Toyota',
        ['model'] = '22TOYOTACOM',
        ['price'] = 4000,
        ['category'] = 'toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `22TOYOTACOM`,
        ['shop'] = 'pdm',
    },
    ['79d'] = {
        ['name'] = 'Hilux 1979',
        ['brand'] = 'Toyota',
        ['model'] = '79d',
        ['price'] = 4000,
        ['category'] = 'toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `79d`,
        ['shop'] = 'pdm',
    },
    -- CDodge
    ['12charger'] = {
        ['name'] = 'Charger 2012',
        ['brand'] = 'Dodge',
        ['model'] = '12charger',
        ['price'] = 4000,
        ['category'] = 'dodge',
        ['categoryLabel'] = 'Dodge',
        ['hash'] = `12charger`,
        ['shop'] = 'pdm',
    },
    -- CChevrolet
    ['18camaro'] = {
        ['name'] = 'Camaro SS 2018',
        ['brand'] = 'Chevrolet',
        ['model'] = '18camaro',
        ['price'] = 4000,
        ['category'] = 'chevrolet',
        ['categoryLabel'] = 'Chevrolet',
        ['hash'] = `18camaro`,
        ['shop'] = 'pdm',
    },
    -- CFord
    ['92anni'] = {
        ['name'] = 'Falcon GT 1992',
        ['brand'] = 'Ford',
        ['model'] = '92anni',
        ['price'] = 4000,
        ['category'] = 'ford',
        ['categoryLabel'] = 'Ford',
        ['hash'] = `92anni`,
        ['shop'] = 'pdm',
    },
}

**Comment by rstreetz** [comment]
what was the fix?
