### ISSUE TITLE
[SUGGESTION] Multiple finance locations

### ISSUE THREAD

**Issue by AntonMars** [qbcore-fivem/qb-vehicleshop#59]
**Is your feature request related to a problem? Please describe.**
It seems that you can only finance a vehicle at one location (PDM) as there is only one set of coordinates in the config.

**Describe the feature you'd like**
Is there a way we could have a finance option at every dealership in the city (PDM, Boats, Air, Luxury, etc.)

**Describe alternatives you've considered**
Possibly a set of coordinates at each shop definition?

**Additional context**
N/A

**Comment by vkaygaming** [comment]
this exactly would be huge
