### ISSUE TITLE
[BUG] SCRIPT ERROR: @qb-vehicleshop/client.lua:101: bad argument #1 to 'gsub' (string expected, got nil)

### ISSUE THREAD

**Issue by an9n6m97s** [qbcore-fivem/qb-vehicleshop#61]
I got this error when i enter in Vehicle Shop ZONE:
**SCRIPT ERROR: @qb-vehicleshop/client.lua:101: bad argument #1 to 'gsub' (string expected, got nil)**
**> [global chunk] (@qb-vehicleshop/client.lua:101)**
**> fn (@qb-vehicleshop/client.lua:246)**

These are the following line:
**local function comma_value(amount)**
    **local formatted = amount**
    **local k**
    **while true do**
        **formatted, k = string.gsub(formatted, '^(-?%d+)(%d%d%d)', '%1,%2') -- 101**
        **if k == 0 then**
            **break**
        **end**
    **end**
    **return formatted**
**end**

Here is an Screen Shot:
https://prnt.sc/f46r0nb21tvS

**Questions (please complete the following information):**
 - When you last updated: 2 days ago
 - Are you using custom resource? which ones? qb-vehicleshop
 - Have you renamed `qb-` to something custom? no

**Comment by citRaTTV** [comment]
This is most likely caused by a lack of vehicle price or config from this line: https://github.com/qbcore-framework/qb-vehicleshop/blob/main/client.lua#L113
