### ISSUE TITLE
Jobs for dealerships

### ISSUE THREAD

**Issue by jessemel** [qbcore-fivem/qb-vehicleshop#62]
Are we able to lock a dealership to multiple jobs instead of just one? If so how? I have tried several ways to lock a dealership to the different police job names and cannot for the life of me figure out what I am doing wrong.

**Comment by citRaTTV** [comment]
Looking at the code, it looks like only a single job is supported right now. Adding support for multiple jobs wouldn't be much work, however there would be a question of where the money goes after a sale. Would it go to the job of the person who sold the vehicle? Or would it go into a specifically configured (separately) job account?

**Comment by AngryMaximus** [comment]
> Looking at the code, it looks like only a single job is supported right now. Adding support for multiple jobs wouldn't be much work, however there would be a question of where the money goes after a sale. Would it go to the job of the person who sold the vehicle? Or would it go into a specifically configured (separately) job account?

just get the player who sold the car, get their job name > addcountmoney Seller.jobname

**Comment by citRaTTV** [comment]
> > Looking at the code, it looks like only a single job is supported right now. Adding support for multiple jobs wouldn't be much work, however there would be a question of where the money goes after a sale. Would it go to the job of the person who sold the vehicle? Or would it go into a specifically configured (separately) job account?
> 
> just get the player who sold the car, get their job name > addcountmoney Seller.jobname 
> 

Yea I think that makes the most sense as well.
