### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by DispersiaRoleplay** [qbcore-fivem/qb-vehicleshop#73]
split pls ox_lib menu with qb-vehicleshop. instead of qb-menu with backdoor. ![image](https://github.com/qbcore-framework/qb-vehicleshop/assets/155019886/4a7b8d4b-82d0-4112-b3ed-e0a29f70f996)

**Comment by ChristianBDev** [comment]
@Psycho66626 what is the problem?

**Comment by DispersiaRoleplay** [comment]
> @Psycho66626 what is the problem?

hello, dear Christian. Combine pls ox_lib menu instead of qb-menu with qb-vehicleshop. 

Cuz qb-menu has a backdoor.
